image: maven:latest

build-job:
  stage: build
  script: mvn clean install
#  script: chmod +x mvnw && ./mvnw package
  artifacts:
    paths:
      - ./target/FlavourFit-0.0.1-SNAPSHOT.jar
  only:
      - bh626198-test

test-job:
  stage: test
  script:
    - mvn test
  only:
    - bh626198-test

deploy-job:
  stage: deploy
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
  only:
    - bh626198-test

