image: docker:latest

services:
  - docker:dind

stages:
  - test-backend
  - build-backend
  - build-frontend
  - deploy-backend
  - deploy-frontend

variables:
  DOCKER_DRIVER: overlay2
  SPRING_OUTPUT_DIRECTORY: target
  REACT_OUTPUT_DIRECTORY: build

test-backend:
  stage: test-backend
  script:
    - cd Backend
    - mvn test
  only:
    - develop

build-backend:
  stage: build-backend
  image: maven:3.6-jdk-11
  script:
    - cd Backend
    - mvn package -DskipTests
    - docker build -t flavour-fit-app .
  artifacts:
    paths:
      - Backend/target/*.jar
  only:
    - develop

build-frontend:
  stage: build-frontend
  image: node:latest
  script:
    - cd Frontend
    - npm install
    - npm run build
  artifacts:
    paths:
      - Frontend/build
  only:
    - develop

deploy-backend:
  stage: deploy-backend
  script:
    - echo "Deploying to Render"
    - # Add commands to deploy Docker image to Render
  only:
    - develop

deploy-frontend:
  stage: deploy-frontend
  script:
    - echo "Deploying to Netlify"
    - # Add commands to deploy frontend build to Netlify
  only:
    - develop