#References
#https://gitlab.com/gitlab-examples/spring-gitlab-cf-deploy-demo/-/blob/master/.gitlab-ci.yml
#https://www.digitalocean.com/community/tutorials/maven-commands-options-cheat-sheet

image: maven:latest

build-job:
  stage: build
  script: mvn clean install
#  script: chmod +x mvnw && ./mvnw package
  artifacts:
    paths:
      - ./target/FlavourFit-0.0.1-SNAPSHOT.jar
  only:
      - main

test-job:
  stage: test
  script:
    - mvn test
  only:
    - main

deploy-job:
  stage: deploy
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
  only:
    - main

