image: maven:latest

build-job:
  stage: build
  script: ./mvnw package
  artifacts:
    paths:
      - target/build.jar
  only:
      - build

test-job:
  stage: test
  script:
    - echo "This job tests something"

